name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --editable ".[test,lint,docs]"
          python -c "import cro.geneea"
          cro.geneea --help
      - name: Format the code
        run: |
          black --check . --exclude docs/
      - name: Sort the imports
        run: |
          isort .
      - name: Lint the code
        run: |
          #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test the code
        run: |
          pip install pytest
          python -X utf8 -m pytest -m domain
          python -X utf8 -m pytest -m client
        env:
          GENEEA_API_KEY: ${{ secrets.GENEEA_API_KEY }}
